accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.CustomSignupView.as_view(), name="signup"),
    path("me/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("settings/", views.SettingView.as_view(), name="settings"),
    path("@<str:username>/follow/", views.AddFollowView.as_view(), name="follow"),
    path("@<str:username>/", views.ProfileView.as_view(), name="profile"),
        # path(
    #     "@<str:username>/followers/", views.FollowerListView.as_view(), name="followers"
    # ),
    path(
        "password-change/",
        views.CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-change/done/",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("new/", views.PostCreateView.as_view(), name="post-create"),
    path("search/", views.SearchView.as_view(), name="search"),
    path(
        "@<str:username>/<slug:post_slug>/",
        views.PostDetailView.as_view(),
        name="post-detail",
    ),
    path("<slug:post_slug>/edit/", views.PostUpdateView.as_view(), name="post-update"),
    path(
        "<slug:post_slug>/delete/", views.PostDeleteView.as_view(), name="post-delete"
    ),
]

urlpatterns += [
    path(
        "<slug:post_slug>/comment/<int:pk>/edit/",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "<slug:post_slug>/comment/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
]

urlpatterns += [
    path("<slug:post_slug>/like/", views.LikeAddView.as_view(), name="like"),
    path("<slug:post_slug>/dislike/", views.DislikeAddView.as_view(), name="dislike"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blogs.feeds import PostsFeeds, AtomSiteNewsFeed
from blogs.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}

context = {
    "sitemaps": sitemaps,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blogs.urls", namespace="blogs")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("feed/rss", PostsFeeds(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("sitemap.xml", sitemap, context, name="django.contrib.sitemaps.views.sitemap"),
]

handler404 = "blogs.error_handlers.handler404"
handler403 = "blogs.error_handlers.handler403"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<div class="container">
  <footer
    class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top"
  >
    <p class="col-md-4 mb-0 text-body-secondary">
      &copy; {% now "Y" %} myBlog
    </p>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item">
        <a
          href="{% url 'django.contrib.sitemaps.views.sitemap' %}"
          class="nav-link px-2 text-body-secondary"
          >Sitemap
        </a>
      </li>
      <li class="nav-item">
        <a
          href="{% url 'post_feed' %}"
          class="nav-link px-2 text-body-secondary"
          >RSS Feed
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'blogs:about' %}" class="nav-link px-2 text-body-secondary">
          About
        </a>
      </li>
    </ul>
  </footer>
</div>

templates/partials/header.html
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div
      class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
    >
      <ul
        class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
      >
        <li>
          <a
            href="/"
            class="nav-link px-2 link-dark fw-bolder"
            style="font-size: 30px"
            >MyBlog
          </a>
        </li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'blogs:search' %}" method="get" role="search">
        <input
          type="search"
          name="q"
          class="form-control"
          placeholder="Search..."
          aria-label="Search"
        />
      </form>

      {% if request.user.is_authenticated %}
      <ul
        class="nav col-12 col-lg-auto mb-2 justify-content-center mb-md-0 px-4"
      >
        <li>
          <a
            href="{% url 'blogs:post-create' %}"
            class="nav-link px-2 text-muted link-primary"
          >
            <i class="fa-regular fa-pen-to-square fa-lg"></i>
            Write
          </a>
        </li>
      </ul>

      <div class="dropdown text-end">
        <a
          href="#"
          class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
         <img
            src="{{ request.user.profile.image.url }}"
            alt="mdo"
            width="32"
            height="32"
            class="rounded-circle"
          /> 
        </a>
        <ul class="dropdown-menu text-small">
          <li>
            <a class="dropdown-item" href="{{ request.user.profile.get_absolute_url }}">
              Profile
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'accounts:settings' %}"
              >Settings
            </a>
          </li>
          <li><hr class="dropdown-divider" /></li>
          <li>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}"
              >Sign out
            </a>
          </li>
        </ul>
      </div>
      {% else %}
      <a
        class="ms-3 btn btn-sm btn-outline-secondary"
        href="{% url 'accounts:login' %}"
      >
        Log in
      </a>
      <a
        class="ms-3 btn btn-sm btn-outline-secondary"
        href="{% url 'accounts:signup' %}"
      >
        Sign up
      </a>
      {% endif %}
    </div>
  </div>
</header>

templates/partials/pagination.html
<nav aria-label="Pagination">
  <hr class="my-0" />
  <ul class="pagination justify-content-center my-4">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}

    {% for num in page.paginator.page_range %}
    {% if page.number == num %}
      <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
      {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
      <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
      </li>
    {% endif %}
    {% endfor %}

    {% if page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
</nav>