accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.CustomSignupView.as_view(), name="signup"),
    path("me/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("settings/", views.SettingView.as_view(), name="settings"),
    path("@<str:username>/follow/", views.AddFollowView.as_view(), name="follow"),
    path("@<str:username>/", views.ProfileView.as_view(), name="profile"),
        # path(
    #     "@<str:username>/followers/", views.FollowerListView.as_view(), name="followers"
    # ),
    path(
        "password-change/",
        views.CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-change/done/",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("new/", views.PostCreateView.as_view(), name="post-create"),
    path("search/", views.SearchView.as_view(), name="search"),
    path(
        "@<str:username>/<slug:post_slug>/",
        views.PostDetailView.as_view(),
        name="post-detail",
    ),
    path("<slug:post_slug>/edit/", views.PostUpdateView.as_view(), name="post-update"),
    path(
        "<slug:post_slug>/delete/", views.PostDeleteView.as_view(), name="post-delete"
    ),
]

urlpatterns += [
    path(
        "<slug:post_slug>/comment/<int:pk>/edit/",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "<slug:post_slug>/comment/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
]

urlpatterns += [
    path("<slug:post_slug>/like/", views.LikeAddView.as_view(), name="like"),
    path("<slug:post_slug>/dislike/", views.DislikeAddView.as_view(), name="dislike"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blogs.feeds import PostsFeeds, AtomSiteNewsFeed
from blogs.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}

context = {
    "sitemaps": sitemaps,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blogs.urls", namespace="blogs")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("feed/rss", PostsFeeds(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("sitemap.xml", sitemap, context, name="django.contrib.sitemaps.views.sitemap"),
]

handler404 = "blogs.error_handlers.handler404"
handler403 = "blogs.error_handlers.handler403"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.urls import reverse

from PIL import Image
from io import BytesIO


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    headline = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Enter a brief headline that describes you or your role",
    )
    about = models.TextField(max_length=500, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse("accounts:profile", kwargs={"username": self.username})


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="following"
    )

    def __str__(self) -> str:
        return f"{self.user.email} Profile"

    def get_absolute_url(self):
        if self.user.username:
            return reverse("accounts:profile", kwargs={"username": self.user.username})
        else:
            # Handle the case where username is empty
            return reverse("blogs:index") 

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Profile

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "username")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email",)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "headline", "about")


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("image",)

accounts/views.py
from django.contrib import messages

from django.contrib.auth import views, get_user_model,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.views import generic
from django.contrib.auth.decorators import login_required

from .forms import CustomUserCreationForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile

from blogs.models import Post

User = get_user_model()


class CustomLoginView(views.LoginView):
    template_name = "accounts/login.html"
    redirect_authenticated_user = True


@login_required
def user_logout(request):
    logout(request)
    return redirect('blogs:index')

class CustomSignupView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("blogs:index")
        return super().dispatch(request, *args, **kwargs)


class SettingView(generic.TemplateView):
    template_name = "accounts/settings.html"


class CustomPasswordChangeView(views.PasswordChangeView):
    success_url = reverse_lazy("accounts:password_change_done")
    template_name = "accounts/password_change_form.html"


class CustomPasswordChangeDoneView(views.PasswordResetDoneView):
    template_name = "accounts/password_change_done.html"


class CustomPasswordResetView(views.PasswordResetView):
    email_template_name = "accounts/password_reset_email.html"
    success_url = reverse_lazy("accounts:password_reset_done")
    template_name = "accounts/password_reset_form.html"


class CustomPasswordResetDoneView(views.PasswordResetDoneView):
    template_name = "accounts/password_reset_done.html"


class CustomPasswordResetConfirmView(views.PasswordResetConfirmView):
    success_url = reverse_lazy("accounts:password_reset_complete")
    template_name = "accounts/password_reset_confirm.html"


class CustomPasswordResetCompleteView(views.PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"


class ProfileView(generic.TemplateView):
    model = Profile
    template_name = "accounts/profile.html"
    context_object_name = 'profile'

    def get_object(self):
        return get_object_or_404(Profile, user__username=self.kwargs['username'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = self.get_object()
        username = self.kwargs.get("username")
        user = get_object_or_404(User, username=username)
        post_list = Post.published.filter(author=user)
        paginator = Paginator(post_list, per_page=2)
        page_number = self.request.GET.get("page")
        posts = paginator.get_page(page_number)
        context["posts"] = posts
        context["user"] = user
        context['followers'] = profile.followers.count()   
        return context


class AddFollowView(generic.View):
    def post(self, request, *args, **kwargs):
        username = self.kwargs.get("username")
        user_to_follow = get_object_or_404(User, username=username)
        profile = user_to_follow.profile  # Assuming Profile is related to User with a OneToOne field
        if request.user.is_authenticated:
            if profile != request.user.profile:
                if profile.followers.filter(id=request.user.id).exists():
                    profile.followers.remove(request.user)
                else:
                    profile.followers.add(request.user)
    def post(self, request, *args, **kwargs):
        username = self.kwargs.get("username")
        user_to_follow = get_object_or_404(User, username=username)
        profile = user_to_follow.profile  # Assuming Profile is related to User with a OneToOne field
        if request.user.is_authenticated:
            if profile != request.user.profile:
                if profile.followers.filter(id=request.user.id).exists():
                    profile.followers.remove(request.user)
                else:
                    profile.followers.add(request.user)
        return redirect('accounts:profile', username=username)

class ProfileEditView(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        u_form = UserUpdateForm(instance=self.request.user)
        p_form = ProfileUpdateForm(instance=self.request.user.profile)

        context = {
            "u_form": u_form,
            "p_form": p_form,
        }
        return render(request, "accounts/profile_edit.html", context)

    def post(self, request, *args, **kwargs):
        u_form = UserUpdateForm(self.request.POST, instance=self.request.user)
        p_form = ProfileUpdateForm(
            self.request.POST,
            self.request.FILES,
            instance=self.request.user.profile,
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect("accounts:profile", request.user.username)

        context = {
            "u_form": u_form,
            "p_form": p_form,
        }
        return render(request, "accounts/profile_edit.html", context)


# class FollowUserView(LoginRequiredMixin, generic.View):
#     def post(self, request, pk, *args, **kwargs):
#         profile = Profile.objects.get(pk=pk)
#         profile.followers.add(self.request.user)
#         return redirect()

# class FollowUserView(LoginRequiredMixin, generic.View):
#     def post(self, request, username, *args, **kwargs):
#         user_to_followe = get_object_or_404(User, username=username)
#         user_profile = request.user.profile

#         user_profile.foll


class FollowerListView(generic.View):
    def get(self, request, *args, **kwargs):
        template_name = "accounts/followers.html"
        return render(request, template_name)


# class FollowerListView(generic.ListView):
#     model = Profile
#     template_name = "accounts/followers.html"

#     def get_queryset(self):
#         return super().get_queryset().filter(followers=)


# class AddFollowView(LoginRequiredMixin, generic.View):
#     def post(self, request, username, *args, **kwargs):
#         profile = get_object_or_404(Profile, user=user)
#         print("-----------")
#         print(profile)
#         print("-----------")
#         # profile.followers.add(self.request.user)
#         # return redirect(profile.ge)


# @login_required
# def follow_user(request, username):
#     if request.method == 'POST':
#         user_to_follow = get_object_or_404(CustomUser, username=username)
#         user_profile = request.user.profile

#         if user_to_follow != request.user:
#             user_to_follow.profile.followers.add(request.user)
#             messages.success(request, f'You are now following {user_to_follow.username}')
#         else:
#             messages.warning(request, 'You cannot follow yourself.')

#     return redirect('users:profile', username=username)

# @login_required
# def unfollow_user(request, username):
#     if request.method == 'POST':
#         user_to_unfollow = get_object_or_404(CustomUser, username=username)
#         user_profile = request.user.profile

#         if user_to_unfollow.profile.followers.filter(username=request.user.username).exists():
#             user_to_unfollow.profile.followers.remove(request.user)
#             messages.success(request, f'You have unfollowed {user_to_unfollow.username}')
#         else:
#             messages.warning(request, f'You were not following {user_to_unfollow.username}')

#     return redirect('users:profile', username=username)

accounts/templates/accounts/followers.html
{% extends 'base.html' %}
{% block title %}
  {% if user.first_name %}
  {{ user.first_name }} {{ user.last_name }} - MyBlog
  {% else %}
  {{ user.username }} - MyBlog
  {% endif %}
{% endblock title %}

{% block content %}
<section>
  <div class="container py-5">
    <div class="row">
      
      <div class="col-lg-8">
        {% if user.first_name %}
        <h1>{{ user.first_name }} {{ user.last_name }}</h1>
        {% else %}
        <h1>{{ user.username }}</h1>
        {% endif %}
        <div class="row">
          <div class="col">
            <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
              <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item active"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">About</a></li>
              </ol>
            </nav>
          </div>
        </div>
        
        <div class="col-lg-12">
          <!-- Blog post-->
          {% for post in posts %}
          <div class="card mb-4">
            <div class="card-body">
              <div class="d-flex align-items-center my-4">
                <a href="{{ post.author.get_absolute_url }}">
                  <img
                  class="rounded-circle me-3"
                  width="40"
                  height="40"
                  src="{{ post.author.profile.image.url }}"
                  alt="..."
                />
                </a>
                <div class="small">
                  <a class="text-decoration-none text-dark" href="{{ post.author.get_absolute_url }}">
                    {% if post.author.first_name %}
                    <div class="fw-bold">{{ post.author.get_full_name }}</div>
                    {% else %}
                    <div class="fw-bold">{{ post.author.username }}</div>
                    {% endif %}
                  </a>
                  <div class="text-muted">{{ post.publish|date:'M j, Y' }}</div>
                </div>
              </div>
              <h2 class="card-title h4">
                <a
                  href="{{ post.get_absolute_url }}"
                  class="text-decoration-none text-dark"
                  >{{ post.title }}</a
                >
              </h2>
              <p class="card-text">{{ post.body }}</p>
              <a
                class="badge bg-secondary text-decoration-none link-light"
                href="#!"
                >Web Design
              </a>
              <span class="text-muted small px-2"
                >{{ post.reading_time_minutes }} min read
              </span>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- Pagination-->
        {% include 'partials/pagination.html' with page=posts %}
        
      </div>

      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body">
            <img
              src="{{ user.profile.image.url }}"
              alt="avatar"
              class="rounded-circle img-fluid"
              style="width: 120px;"
            />
            {% if user.first_name %}
            <h5 class="mt-3">{{ user.get_full_name }}</h5>
            {% else %}
            <h5 class="mt-3">{{ user.username }}</h5>
            {% endif %}
            <a class="text-decoration-none link-secondary" href="#">30 followers</a>
            {% if user.headline %}
            <p class="text-muted mt-3 mb-1">{{ user.headline }}</p>
            {% endif %}
            <div class="d-flex justify-content mb-2">
              {% if request.user == user %}
              <a
              class="text-decoration-none py-2"
              href="{% url 'accounts:profile_edit' %}">
              Edit profile
              </a>
              {% else %}
              <button class="btn btn-success my-2" type="submit">Follow</button>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Log In{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <form action="" method="post">
      {% csrf_token %} {{ form|crispy }}
      <button class="btn btn-success my-2" type="submit">Sign in</button>
    </form>
    <div class="py-2">
      <span>
        <a href="{% url 'accounts:password_reset' %}">Forgot your password?</a>
      </span>
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Log Out{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <div class="py-2">
        <form method="post" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <button type="submit">logout</button>
        </form>
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
{% block title %}Password Change Successful{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Password change successful</h1>
    <p>Your password was changed.</p>
    {% endblock content %}
  </div>
</section>

accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%}PasswordChange{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Password change</h1>
    <p>
      Please enter your old password, for security's sake, and then enter your
      new password twice so we can verify you typed it in correctly.
    </p>
    <form method="POST">
      {% csrf_token %} {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Change my password" />
    </form>
    {% endblock content %}
  </div>
</section>

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset complete{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Password reset complete</h1>
    <p>Your new password has been set.</p>
    <p>You can log in now
    <a href="{% url 'accounts:login' %}">Log In</a>.</p>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Enter new password{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Set a new password!</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Change my password">
    </form>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% block title %}Email Sent{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Check your inbox.</h1>
    <p>We've emailed you instructions for setting your password.
    You should receive the email shortly!</p>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
You've requested to reset your password.

Please go to the following URL to enter your new password:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Forgot Your Password?{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <form action="" method="post">
      {% csrf_token %} {{ form|crispy }}
      <input
        class="btn btn-success"
        type="submit"
        value="Send me instructions!"
      />
    </form>
    {% endblock content %}
  </div>
</section>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}
  {% if user.first_name %}
  {{ user.get_full_name }} - MyBlog
  {% else %}
  {{ user.username }} - MyBlog
  {% endif %}
{% endblock title %}

{% block content %}
<section>
  <div class="container py-5">
    <div class="row">
      
      <div class="col-lg-8">
        {% if user.first_name %}
        <h1>{{ user.get_full_name }}</h1>
        {% else %}
        <h1>{{ user.username }}</h1>
        {% endif %}
        <div class="row">
          <div class="col">
            <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
              <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item active"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">About</a></li>
              </ol>
            </nav>
          </div>
        </div>
        
        <div class="col-lg-12">
          <!-- Blog post-->
          {% for post in posts %}
          <div class="card mb-4">
            <div class="card-body">
              <div class="d-flex align-items-center my-4">
                <a href="{{ post.author.get_absolute_url }}">
                  <img
                  class="rounded-circle me-3"
                  width="40"
                  height="40"
                  src="{{ post.author.profile.image.url }}"
                  alt="..."
                />
                </a>
                <div class="small">
                  <a class="text-decoration-none text-dark" href="{{ post.author.get_absolute_url }}">
                    {% if post.author.first_name %}
                    <div class="fw-bold">{{ post.author.get_full_name }}</div>
                    {% else %}
                    <div class="fw-bold">{{ post.author.username }}</div>
                    {% endif %}
                  </a>
                  <div class="text-muted">{{ post.publish|date:'M j, Y' }}</div>
                </div>
              </div>
              <h2 class="card-title h4">
                <a
                  href="{{ post.get_absolute_url }}"
                  class="text-decoration-none text-dark"
                  >{{ post.title }}</a
                >
              </h2>
              <p class="card-text">{{ post.body }}</p>
              <span class="text-muted small px-2"
                >{{ post.reading_time_minutes }} min read
              </span>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- Pagination-->
        {% include 'partials/pagination.html' with page=posts %}
        
      </div>

      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body">
            <img
              src="{{ user.profile.image.url }}"
              alt="avatar"
              class="rounded-circle img-fluid"
              style="width: 120px;"
            />
            <h5 class="mt-3">
              {% if user.first_name %}
              {{ user.get_full_name }}
              {% else %}
              {{ user.username }}
              {% endif %}
            </h5>

            {% comment %} <a class="text-decoration-none link-secondary" href="{% url "users:followers" user.username %}">{{ user.followers.all.count }} followers</a> {% endcomment %}
            <a class="text-decoration-none link-secondary" href="#">{{followers}} followers</a> 
            
            {% if user.headline %}
            <p class="text-muted mt-3 mb-1">{{ user.headline }}</p>
            {% endif %}
            
            <div class="d-flex justify-content mb-2">
              {% if request.user == user %}
              <a
              class="text-decoration-none py-2"
              href="{% url 'accounts:profile_edit' %}">
              Edit profile
              </a>
              {% else %}
              <form action="{% url 'accounts:follow' user.username %}" method="post">
                {% csrf_token %}
                <button class="btn btn-success my-2" type="submit">Follow</button>
              </form>
              {% endif %} 
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Settings{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <div class="content-section">
      <div class="media py-4">
        <img
          class="rounded-circle account-img"
          src="{{ user.profile.image.url }}"
        />
      </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
          {{ u_form|crispy }} {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-success" type="submit">Update</button>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock title %}

{% block content %}
<section>
  <div class="container py-5">
    <div class="row justify-content-center">
      
      <div class="col-lg-8">
        <div class="row">
          <h1>Settings</h1>
          <div class="col">
            <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
              <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item active">
                  <a class="text-decoration-none" href="#">Account</a>
                </li>
              </ol>
            </nav>
          </div>
        </div>
        
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-4">
                <p class="mb-0">Username and subdomain</p>
              </div>
              <div class="col-sm-8">
                <p class="text-muted mb-0">@{{ request.user.username }}</p>
              </div>
            </div>
            <hr />
            <div class="row">
              <div class="col-sm-4">
                <p class="mb-0">Email address</p>
              </div>
              <div class="col-sm-8">
                <p class="text-muted mb-0">{{ request.user.email }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h2>Sign Up</h2>
    <form method="post">
      {% csrf_token %} {{ form|crispy }}
      <button class="btn btn-success" type="submit">Sign Up</button>
    </form>
  </div>
</section>
{% endblock content %}