accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.CustomSignupView.as_view(), name="signup"),
    path("me/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("settings/", views.SettingView.as_view(), name="settings"),
    path("@<str:username>/follow/", views.AddFollowView.as_view(), name="follow"),
    path("@<str:username>/", views.ProfileView.as_view(), name="profile"),
        # path(
    #     "@<str:username>/followers/", views.FollowerListView.as_view(), name="followers"
    # ),
    path(
        "password-change/",
        views.CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-change/done/",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("new/", views.PostCreateView.as_view(), name="post-create"),
    path("search/", views.SearchView.as_view(), name="search"),
    path(
        "@<str:username>/<slug:post_slug>/",
        views.PostDetailView.as_view(),
        name="post-detail",
    ),
    path("<slug:post_slug>/edit/", views.PostUpdateView.as_view(), name="post-update"),
    path(
        "<slug:post_slug>/delete/", views.PostDeleteView.as_view(), name="post-delete"
    ),
]

urlpatterns += [
    path(
        "<slug:post_slug>/comment/<int:pk>/edit/",
        views.CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "<slug:post_slug>/comment/<int:pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
]

urlpatterns += [
    path("<slug:post_slug>/like/", views.LikeAddView.as_view(), name="like"),
    path("<slug:post_slug>/dislike/", views.DislikeAddView.as_view(), name="dislike"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blogs.feeds import PostsFeeds, AtomSiteNewsFeed
from blogs.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}

context = {
    "sitemaps": sitemaps,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blogs.urls", namespace="blogs")),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("feed/rss", PostsFeeds(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path("sitemap.xml", sitemap, context, name="django.contrib.sitemaps.views.sitemap"),
]

handler404 = "blogs.error_handlers.handler404"
handler403 = "blogs.error_handlers.handler403"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.conf import settings
from django.db import models
from django.db.models.query import QuerySet
from django.template.defaultfilters import slugify
from django.urls import reverse



class CategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(parent=None)


class SubCategoryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(parent__isnull=False)


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="children",
    )

    objects = models.Manager()
    top_category = CategoryManager()
    sub_category = SubCategoryManager()

    class Meta:
        ordering = ["title"]
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)


class PublishedManager(models.Manager):
    """
    Custom Manager
    Returns: Post with 'PUBLISHED' status
    """

    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    overview = models.TextField(
        max_length=1000, help_text="Enter a brief overview or summary of the post here."
    )
    content = models.TextField()
    thumbnail = models.ImageField(
        upload_to="post_images/",
        null=True,
        blank=True,
        help_text="Upload an image to accompany this post.",
    )
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )
    reading_time_minutes = models.PositiveIntegerField(
        default=2,
        help_text="Enter the estimated reading time in minutes for this blog post.",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts",
    )
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="likes"
    )
    dislikes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="dislikes"
    )
    publish = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()  # default Manager
    published = PublishedManager()  # custom Manager

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blogs:post-detail",
            kwargs={"username": self.author.username, "post_slug": self.slug},
        )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    edited = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self) -> str:
        return f"Commented by {self.author.email} on post {self.post}"

    def get_absolute_url(self):
        return reverse(
            "blogs:post-detail",
            kwargs={"username": self.author.username, "post_slug": self.post.slug},
        )

blogs/forms.py
from django import forms

from .models import Post, Comment


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "thumbnail", "content", "reading_time_minutes")


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

    def __init__(self, *args, **kwargs):
        super(CommentModelForm, self).__init__(*args, **kwargs)
        self.fields["comment"].widget.attrs.update(
            (
                {
                    "class": "form-control",
                    "rows": "3",
                    "placeholder": "Join the discussion and leave a comment!",
                }
            )
        )

blogs/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, View
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import PostModelForm, CommentModelForm
from .models import Post, Comment

User = get_user_model()


class IndexView(TemplateView):
    template_name = "blogs/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.published.all()
        paginator = Paginator(post_list, per_page=10)
        page_number = self.request.GET.get("page")
        posts = paginator.get_page(page_number)
        context["posts"] = posts
        return context


class AboutView(TemplateView):
    template_name = "about.html"


class SearchView(TemplateView):
    template_name = "blogs/search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("q", "")
        if query:
            results = Post.published.filter(title__icontains=query)
        context["results"] = results
        return context


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    form_class = PostModelForm
    success_message = "The post has been created successfully."
    template_name = "blogs/post_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.status = Post.Status.PUBLISHED
        return super().form_valid(form)


class CommentGetView(DetailView):
    model = Post
    context_object_name = "post"
    slug_field = "slug"
    slug_url_kwarg = "post_slug"
    template_name = "blogs/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = post.comments.filter(active=True)
        total_comments = comments.count()
        context["form"] = CommentModelForm()
        context["comments"] = comments
        context["total_comments"] = total_comments
        return context


class CommentPostView(LoginRequiredMixin, SingleObjectMixin, FormView):
    model = Post
    form_class = CommentModelForm
    slug_field = "slug"
    slug_url_kwarg = "post_slug"
    template_name = "blogs/post_detail.html"

    def post(self, request, *args, **kwargs):
        # Ensure the object is retrieved and set
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        # Ensure context with the object is provided on form invalid
        context = self.get_context_data(form=form)
        context['object'] = self.object
        return self.render_to_response(context)
    
    def get_success_url(self):
        return reverse("blogs:post-detail", kwargs={"username": self.object.author.username, "post_slug": self.object.slug})


class PostDetailView(DetailView):
    def get(self, request, *args, **kwargs):
        view = CommentGetView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPostView.as_view()
        return view(request, *args, **kwargs)


class PostUpdateView(
    LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView
):
    model = Post
    context_object_name = "post"
    form_class = PostModelForm
    slug_field = "slug"
    slug_url_kwarg = "post_slug"
    success_message = "The post has been updated successfully."
    template_name = "blogs/post_update.html"

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user


class PostDeleteView(
    LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView
):
    model = Post
    context_object_name = "post"
    slug_field = "slug"
    slug_url_kwarg = "post_slug"
    success_message = "The post has been deleted successfully."
    success_url = reverse_lazy("blogs:index")
    template_name = "blogs/post_delete.html"

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentModelForm
    slug_field = "slug"
    slug_url_kwarg = "post_slug"
    template_name = "blogs/comment_update.html"

    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user

    def form_valid(self, form):
        form.instance.edited = True
        return super().form_valid(form)


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    context_object_name = "comment"
    slug_field = "slug"
    slug_url_kwarg = "post_slug"
    template_name = "blogs/comment_delete.html"

    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class LikeAddView(LoginRequiredMixin, View):
    def post(self, request, post_slug, *args, **kwargs):
        post = get_object_or_404(Post, slug=post_slug)

        is_disliked = False
        for dislike in post.dislikes.all():
            if dislike == self.request.user:
                is_disliked = True
                break

        # if post is already disliked, the dislike will be removed and the post will be liked
        # because a user can not like and dislike the same post at same time
        if is_disliked:
            post.dislikes.remove(self.request.user)

        is_liked = False
        for like in post.likes.all():
            if like == self.request.user:
                is_liked = True
                break

        if not is_liked:  # not liked the post
            post.likes.add(self.request.user)

        if is_liked:  # already liked the post
            post.likes.remove(self.request.user)

        return redirect(post.get_absolute_url())


class DislikeAddView(LoginRequiredMixin, View):
    def post(self, request, post_slug, *args, **kwargs):
        post = get_object_or_404(Post, slug=post_slug)

        is_liked = False
        for like in post.likes.all():
            if like == self.request.user:
                is_liked = True
                break

        if is_liked:
            post.likes.remove(self.request.user)

        is_disliked = False
        for dislike in post.dislikes.all():
            if dislike == self.request.user:
                is_disliked = True
                break

        if not is_disliked:
            post.dislikes.add(self.request.user)

        if is_disliked:
            post.dislikes.remove(self.request.user)

        return redirect(post.get_absolute_url())

blogs/templates/blogs/comment_delete.html
{% extends "base.html" %}
{% block title %}Comment delete - MyBlog{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Delete</h1>
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete the comment <b>"{{ comment.comment }}"</b>?</p>
      <a
        href="{{ request.META.HTTP_REFERER }}"
        class="btn btn-primary"
        type="submit"
        >Cancel</a
      >
      <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
  </div>
</section>
{% endblock content %}

blogs/templates/blogs/comment_form.html
<form class="mb-4" action="" method="post">
  {% csrf_token %} {{ form }}
  <div style="display: flex; justify-content: flex-end">
    <button class="btn btn-success my-2" type="submit">Comment</button>
  </div>
</form>

blogs/templates/blogs/comment_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Update comment - MyBlog{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container px-5 py-5">
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <a
        href="{{ request.META.HTTP_REFERER }}"
        class="btn btn-primary"
        type="submit"
        >Back</a
      >
      <button class="btn btn-success ml-2" type="submit">Update</button>
    </form>
  </div>
</section>
{% endblock content %}

blogs/templates/blogs/comments.html
<section>
  <div class="card bg-light">
    <div class="card-body">
      <!-- Comment form-->
      {% include 'blogs/comment_form.html' %}
      <!-- Single comment-->
      {% for comment in comments %}
      <div class="d-flex py-2">
        <div class="flex-shrink-0">
         <img
            class="rounded-circle"
            width="40"
            height="40"
            src="{{ comment.author.profile.image.url }}"
            alt="..."
          />
        </div>
        <div class="ms-3">
          <div>
            <span class="fw-bold">
              <a
                class="text-decoration-none text-dark"
                href="{{ comment.author.get_absolute_url }}"
              >
                {% if comment.author.firstname %}
                {{ comment.author.get_full_name }}
                {% else %}
                {{ comment.author.username }}
                {% endif %}
              </a>
            </span>

            {% if comment.author == post.author %}
            <span class="ms-1 me-1 badge text-bg-success">AUTHOR</span>
            {% endif %} &middot;

            {% if comment.edited %}
            <span>(edited)</span>
            &middot;
            {% endif %}
            
            <span class="text-muted">{{ comment.created|timesince }} ago</span>
          </div>
          {{ comment.comment }}
        </div>

        <div class="ms-auto d-flex align-items-center">
          {% if request.user == comment.author %}
          <div>
            <a
              class="text-dark link-primary"
              href="{% url 'blogs:comment-update' post_slug=comment.post.slug pk=comment.pk %}"
            >
              <i class="fa fa-edit fa-lg"></i>
            </a>
          </div>
          <div class="ms-3">
            <a
              class="text-dark link-primary"
              href="{% url 'blogs:comment-delete' comment.post.slug comment.pk %}"
            >
              <i class="fa fa-trash fa-lg"></i>
            </a>
          </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

blogs/templates/blogs/index.html
{% extends 'base.html' %}

{% block content %}
{% if not request.user.is_authenticated %}
<main class="flex-shrink-0">
  <section class="py-5 bg-light">
    <div class="container px-5">
      <div class="card border-0 rounded-3 overflow-hidden">
        <div class="card-body p-0 bg-light">
          <div class="row gx-0">
            <div class="col-lg-6 col-xl-5 py-lg-5">
              <div class="p-4 p-md-5">
                <div class="h1 fw-bolder">Stay curious.</div>
                <p>Discover stories, thinking, and expertise from writers on any topic.</p>
                <a class="stretched-link text-decoration-none" href="{% url 'accounts:login' %}">
                  Start reading
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="py-5">
    <div class="container px-5">
      <div class="row justify-content-center">
        <div class="col-xl-8">
          <h2 class="fw-bolder fs-5 mb-4">Trending on MyBlog</h2>
          <!-- News item-->
          <div class="mb-4">
            <div class="small text-muted">May 12, 2023</div>
            <a class="link-dark" href="#!"
              ><h3>
                Start Bootstrap releases Bootstrap 5 updates for templates and
                themes
              </h3>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

<hr>

{% endif %}

<div class="container py-4">
  <div class="row">
    <!-- Blog entries-->
    <div class="col-lg-8">
      <div class="row">
        <div class="col-lg-12">
          <!-- Blog post-->
          {% for post in posts %}
          <div class="card mb-4">
            <div class="card-body">
              <div class="d-flex align-items-center my-4">
                <a href="{{ post.author.get_absolute_url }}">
                  <img
                  class="rounded-circle me-3"
                  width="40"
                  height="40"
                  src="{{ post.author.profile.image.url }}"
                  alt="..."
                /> 
                </a>
                <div class="small">
                  <a class="text-decoration-none text-dark" href="{{ post.author.get_absolute_url }}">
                    {% if post.author.first_name %}
                    <div class="fw-bold">{{ post.author.get_full_name }}</div>
                    {% else %}
                    <div class="fw-bold">{{ post.author.username }}</div>
                    {% endif %}
                  </a>
                  <div class="text-muted">{{ post.publish|date:'M j, Y' }}</div>
                </div>
              </div>
              <h2 class="card-title h4">
                <a
                  href="{{ post.get_absolute_url }}"
                  class="text-decoration-none text-dark"
                  >{{ post.title }}</a
                >
              </h2>
              <p class="card-text">{{ post.overview|truncatewords:50 }}</p>

              <span class="text-muted small px-2"
                >{{ post.reading_time_minutes }} min read
              </span>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <!-- Pagination-->
      {% include 'partials/pagination.html' with page=posts %}
    </div>

    <!-- Side widgets-->
    <div class="col-lg-4">
    </div>
  </div>
</div>
{% endblock content %}

blogs/templates/blogs/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}New post - MyBlog{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container px-5 py-5">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form|crispy }}
      <button class="btn btn-success ml-2" type="submit">Publish</button>
    </form>
  </div>
</section>
{% endblock content %}

blogs/templates/blogs/post_delete.html
{% extends "base.html" %}
{% block title %}Delete | {{ post.title }}{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container">
    <h1>Delete</h1>
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete the post <b>"{{ post.title }}"</b>?</p>
      <a
        href="{{ request.META.HTTP_REFERER }}"
        class="btn btn-primary"
        type="submit"
        >Cancel</a
      >
      <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
  </div>
</section>
{% endblock content %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load markdown_extras %}
{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<main class="flex-shrink-0">
  <!-- Page Content-->
  <section class="py-5">
    <div class="container px-5 my-5">
      <div class="col-lg-9 mx-auto">
        <!-- Post content-->
        <article>
          <!-- Post header-->
          <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
            <div class="d-flex align-items-center mt-lg-4 mb-4">
              <a href="{{ post.author.get_absolute_url }}">
             <img
                  class="rounded-circle"
                  width="40"
                  height="40"
                  src="{{ post.author.profile.image.url }}"
                  alt="..."
                />
              </a>
              <div class="ms-3">
                <div class="d-inline-flex align-items-center">
                  <span class="fw-bold">
                    <a
                    class="text-decoration-none text-dark"
                    href="{{ post.author.get_absolute_url }}"
                    >
                      {% if post.author.first_name %}
                      {{ post.author.get_full_name }}
                      {% else %}
                      {{ post.author.username }}
                      {% endif %}
                    </a>
                  </span>
                  &middot;
                  <span>
                    <form class="" action="{% url 'accounts:follow' user.username %}" method="post">
                      {% csrf_token %}
                      <button class="btn btn-link my-2" type="submit">Follow</button>
                    </form>
                  </span>
                </div>
                <div class="text-muted">
                  <span>{{ post.reading_time_minutes }} min read</span> &middot;
                  <span>{{ post.publish|date }}</span>
                </div>
              </div>

              {% if request.user == post.author %}
              <div class="ms-3">
                <a
                  class="btn btn-success"
                  href="{% url 'blogs:post-update' post.slug %}"
                  >Update
                </a>
                <a
                  class="btn btn-danger"
                  href="{% url 'blogs:post-delete' post.slug %}"
                  >Delete
                </a>
              </div>
              {% endif %}
            </div>

            <div class="d-flex align-items-center mt-lg-4 mb-4">
              <!-- like count-->
              <div class="ms-1 d-flex align-items-center">
                <div class="py-2">
                    <form action="{% url 'blogs:like' post.slug %}" method="post">
                      {% csrf_token %}
                      <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                        {% if request.user in post.likes.all %}
                        <i class="fa fa-thumbs-up fa-lg"></i>
                        {% else %}
                        <i class="fa-regular fa-thumbs-up fa-lg"></i>
                        {% endif %}
                      </button>
                    </form>
                </div>
                <span class="text-muted">{{ post.likes.all.count }}</span>
              </div>
              <!-- unlike count-->
              <div class="ms-4 d-flex align-items-center">
                <div class="py-2">
                    <form action="{% url 'blogs:dislike' post.slug %}" method="post">
                      {% csrf_token %}
                      <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                        {% if request.user in post.dislikes.all %}
                        <i class="fa fa-thumbs-down fa-lg"></i>
                        {% else %}
                        <i class="fa-regular fa-thumbs-down fa-lg"></i>
                        {% endif %}
                    </form>
                </div>
                <span class="text-muted">{{ post.dislikes.all.count }}</span>
              </div>
              <!-- comments count-->
              <div class="ms-4">
                <div class="py-2">
                  <span class="text-muted">
                    <i class="fa-regular fa-comment fa-lg"></i>
                  </span>
                  <span class="text-muted ms-1">{{ total_comments }} comment{{ total_comments|pluralize }}</span>
                </div>
              </div>
            </div>

          </header>
          <!-- Preview image figure-->
          <figure class="mb-4">
            {% if post.thumbnail %}
            <img
              class="img-fluid rounded"
              src="{{ post.thumbnail.url }}"
              alt="..."
            />
            {% endif %}
          </figure>
          <!-- Post content-->
          <section class="mb-5">
            <div class="content">
              {{ post.content|markdown|safe }}
            </div>
          </section>
        </article>
        <!-- Comments section-->
        {% include 'blogs/comments.html' %}
      </div>
    </div>
  </section>
</main>
{% endblock content %}

blogs/templates/blogs/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update post - MyBlog{% endblock title %}

{% block content %}
<section class="py-5">
  <div class="container px-5 py-5">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form|crispy }}
      <a
        href="{{ request.META.HTTP_REFERER }}"
        class="btn btn-primary"
        type="submit"
        >Back</a
      >
      <button class="btn btn-success ml-2" type="submit">Update</button>
    </form>
  </div>
</section>
{% endblock content %}